.MODEL SMALL
.STACK 100H

;--------------------------------------
;	SEGMENTO DE DATOS
;--------------------------------------
.DATA

MSG	DB	'HOLA MUNDO$'
FPIX	DW	10
CPIX	DW	0

POS_CURSOR MACRO FIL, COL		;UN TIPO DE "METODO" QUE RECIBE 2 PARAMETROS
	MOV AH, 02H
	MOV BH, 00
	MOV DH, FIL
	MOV DL, COL
	INT 10H						;INTERRUPCION DE VIDEO
ENDM

;--------------------------------------
;	SEGMENTO DE CODIGO
;--------------------------------------
.CODE

MAIN PROC FAR
	MOV	AX, @DATA
	MOV	DS, AX
	MOV	ES, AX
	MOV	AX, 0600H
	
	CALL MODEVIDEO
	
	;--------
	MOV CPIX, 10D
	CALL DRAWLINE		;PINTAR UNA LINEA DE PIXELES EN LA POSICION FPIX Y CPIX

	MOV CPIX, 10D
	ADD FPIX, 5D
	CALL DRAWLINE

	MOV CPIX, 10D
	ADD FPIX, 5D
	CALL DRAWLINE

	;ESTO ES MEJOR HACERLO CON BUCLES
	;--------
	
	POS_CURSOR 10, 8

	LEA	DX, MSG
	MOV	AH, 9H		;VISUALIZACION CADENA DE CARACTERES
	INT	21H
	
	MOV AH, 00H
	INT 16H			;INTERRUPCION DE TECLADO

	MOV AH, 4CH
	INT 21H			;INTERRUPCION CIERRE DE PROGRAMA
MAIN ENDP

MODEVIDEO PROC
	MOV AH, 00H
	MOV AL, 12H
	INT 10H
	MOV AH, 0BH
	MOV BH, 00H
	MOV BL, 05H
	INT 10H
	RET
MODEVIDEO ENDP

DRAWLINE PROC NEAR
	MOV CX, 300
CICLO:
	PUSH CX
	MOV AL, 0AH
	MOV BX, 00
	MOV CX, CPIX
	MOV DX, FPIX
	MOV AH, 0CH
	INT 10H
	INC CPIX
	POP CX
	LOOP CICLO
	RET
DRAWLINE ENDP
END
;--------------------------------------
;	SEGMENTO DE CODIGO
;--------------------------------------
